### ISSUE TITLE
K có thanh cuộn ngang, nội dung thì chưa fit

### ISSUE THREAD

**Issue by hoangledinh65** [lidi-team/okrs-v2#120]
**Describe the bug**
![image](https://user-images.githubusercontent.com/26743914/102717646-3441c880-4316-11eb-941f-72ce64d70304.png)

**Comment by thaycacac** [comment]
Duplicate issue

**Comment by hoangledinh65** [comment]
Issue giống nhau nhưng, 2 cái màn hình khác nhau mà ông. @thaycacac
