### ISSUE TITLE
Lỗi hệ thống khi click "Xem chi tiết" "Lịch sử cập nhật tiến độ"

### ISSUE THREAD

**Issue by hoangledinh65** [lidi-team/okrs-v2#122]
**Describe the bug**
![image](https://user-images.githubusercontent.com/26743914/102717802-440ddc80-4317-11eb-843f-cd8efe46d087.png)
![image](https://user-images.githubusercontent.com/26743914/102717804-48d29080-4317-11eb-883a-cbd0f4bf7de8.png)

**Comment by thaycacac** [comment]
Cái này do ngày trước test bug. sau khi clear sẽ hết lỗi
