### ISSUE TITLE
KR con chưa liên kết với KR cha 

### ISSUE THREAD

**Issue by hoangledinh65** [lidi-team/okrs-v2#132]
**Describe the bug**

**Comment by thaycacac** [comment]
Cái này cụ thể là như nào @Rubixxx  ơi?

**Comment by hoangledinh65** [comment]
KR con khi tạo sẽ liên kết đến KR cha, tương tự như objective. Nhưng ở phần detail, thì chỉ thể hiện objective cha mà k có KR cha @thaycacac  
![image](https://user-images.githubusercontent.com/26743914/102798290-75ec7500-43e3-11eb-928f-a0de506ee83e.png)
