### ISSUE TITLE
công thức suggest đang có vấn đề, khi chưa chọn độ tự tin.

### ISSUE THREAD

**Issue by hoangledinh65** [lidi-team/okrs-v2#134]
**Describe the bug**
![image](https://user-images.githubusercontent.com/26743914/102739714-77d11c80-4380-11eb-8860-c651d8f7a8ef.png)
![image](https://user-images.githubusercontent.com/26743914/102739727-7ef82a80-4380-11eb-9eb7-8c0066d032bf.png)
![image](https://user-images.githubusercontent.com/26743914/102739733-84557500-4380-11eb-99a2-78a84b62bed6.png)
![image](https://user-images.githubusercontent.com/26743914/102739735-89b2bf80-4380-11eb-8f78-ab1f3463bdb9.png)

**Comment by TungBeo199x** [comment]
công thức này bị làm sao thế
