### ISSUE TITLE
Hiển thị thông tin của Trọng số 

### ISSUE THREAD

**Issue by hoangledinh65** [lidi-team/okrs-v2#136]

**Comment by thaycacac** [comment]
Trả thêm trọng số cho objective. API trả thêm bạn ơi

**Comment by TungBeo199x** [comment]
Oke. trả về thêm trường weight nhé.
nhưng mà hiển thị ở chỗ nào đấy?
@Rubixxx  log bug thêm cả ảnh vào nữa nhé.
