### ISSUE TITLE
Quản lý dự án của Admin đang k cập nhật được 

### ISSUE THREAD

**Issue by hoangledinh65** [lidi-team/okrs-v2#146]
**Describe the bug**
![image](https://user-images.githubusercontent.com/26743914/102783730-f7390d00-43cd-11eb-8ead-0bbcfe726199.png)
![image](https://user-images.githubusercontent.com/26743914/102783746-fe601b00-43cd-11eb-90fd-074ac09a45fb.png)
![image](https://user-images.githubusercontent.com/26743914/102783761-04ee9280-43ce-11eb-9573-07be99e7c095.png)
![image](https://user-images.githubusercontent.com/26743914/102783786-0e77fa80-43ce-11eb-9547-c676afe18a3b.png)

**Comment by nolann-dev** [comment]
![image](https://user-images.githubusercontent.com/56147592/102792828-9adcea00-43db-11eb-9e22-65182c7b65fb.png)
![image](https://user-images.githubusercontent.com/56147592/102792881-aa5c3300-43db-11eb-8fad-90bb9b005158.png)
Không thay đổi được pm dự án

**Comment by hoangledinh65** [comment]
Vậy thì cần disable trường đó đi ae nhé. @ifuncoding
