### ISSUE TITLE
Lần đầu mở dialog để tạo KR mới, click vào ô để nhập tên KR thì nó lại tạo ra 1 KR mới bên dưới 

### ISSUE THREAD

**Issue by hoangledinh65** [lidi-team/okrs-v2#150]
**Describe the bug**
![image](https://user-images.githubusercontent.com/26743914/102841902-5df31080-4438-11eb-8c8d-1b096abc1d78.png)
![image](https://user-images.githubusercontent.com/26743914/102841937-6fd4b380-4438-11eb-8720-d3e9bf075c70.png)

**Comment by thaycacac** [comment]
Sao xảy ra case này được nhỉ?
