### ISSUE TITLE
Xem lịch sử checkin thì k thể để cho user update với tạo checkin ngay trong đó được. Chỉ cho xem thôi 

### ISSUE THREAD

**Issue by hoangledinh65** [lidi-team/okrs-v2#153]
**Describe the bug**
![image](https://user-images.githubusercontent.com/26743914/102844015-11f69a80-443d-11eb-8978-aec7eea43deb.png)
![image](https://user-images.githubusercontent.com/26743914/102844054-2c307880-443d-11eb-9640-94e59d5b0a0a.png)

**Comment by thaycacac** [comment]
![image](https://user-images.githubusercontent.com/29374426/103058672-70568100-45d5-11eb-8836-72bebb8b56ee.png)
Phần này @TungBeo199x  trả status overdue nhé
