### ISSUE TITLE
Biểu đồ "Lịch sử tiến độ" khi sếp duyệt checkin chưa work trong khi thực tế đã có những lần checkin trước 

### ISSUE THREAD

**Issue by hoangledinh65** [lidi-team/okrs-v2#154]
**Describe the bug**
![image](https://user-images.githubusercontent.com/26743914/102844430-0b1c5780-443e-11eb-82cc-7c8ddf75b4a7.png)
![image](https://user-images.githubusercontent.com/26743914/102845000-2cca0e80-443f-11eb-979f-10b1c4a75aa6.png)

**Comment by thaycacac** [comment]
Do data chưa clear thôi bn

**Comment by thaycacac** [comment]
Resolved!!!
