### ISSUE TITLE
Nếu có nhiều thay đổi tiến độ trong 1 ngày, biểu đồ lịch sử tiến độ chỉ là 1 đường thẳng từ 0 - điểm cao nhất -> không thể hiện được các giá trị ở giữa 

### ISSUE THREAD

**Issue by hoangledinh65** [lidi-team/okrs-v2#155]
**Describe the bug**
![image](https://user-images.githubusercontent.com/26743914/102845180-8c281e80-443f-11eb-9182-d9efee5a8208.png)

**Comment by thaycacac** [comment]
Biểu đồ thư viện bạn ơi. đừng làm khó nhau nữa đc hem?
