### ISSUE TITLE
Cho phép khi gõ trực tiếp vào phần "Tiến độ thực tế" sẽ xảy ra trường hợp user gõ 1 số k thực tế. Nên disable phần gõ text và để gtri tối đa là 100%

### ISSUE THREAD

**Issue by hoangledinh65** [lidi-team/okrs-v2#157]
**Describe the bug**
![image](https://user-images.githubusercontent.com/26743914/102849893-b3381d80-444a-11eb-86a6-fd193150acb9.png)
![image](https://user-images.githubusercontent.com/26743914/102850055-20e44980-444b-11eb-98f0-2d21c3f9e207.png)

**Comment by thaycacac** [comment]
Cái case này thực tế k xảy ra mà chỉ có người dùng phá !!! với nữa là phải để thế vì ví dụ nó làm hơn 100% thì sao?
