### ISSUE TITLE
Phần "Ngày checkin tiếp theo" cần style lại 

### ISSUE THREAD

**Issue by hoangledinh65** [lidi-team/okrs-v2#162]
**Describe the bug**
![image](https://user-images.githubusercontent.com/26743914/103010685-45374780-456b-11eb-9862-c68e7ac2b943.png)

**Comment by hoangledinh65** [comment]
@thaycacac Đã done đâu mà close thế ông

**Comment by thaycacac** [comment]
Viết detail đi. biết style lại là như nào đâu ô?

**Comment by thaycacac** [comment]
Resolved
