### ISSUE TITLE
Vẫn có thể tạo check in sau khi đã hoàn thành OKR

### ISSUE THREAD

**Issue by TungBeo199x** [lidi-team/okrs-v2#164]
đăng nhập với email
xem check-in của tôi có okr đã hoàn thành
![image](https://user-images.githubusercontent.com/45735121/103016500-b7f8f080-4574-11eb-9bda-e12ff5f12aa9.png)
vào xem lịch sử
![image](https://user-images.githubusercontent.com/45735121/103016530-c2b38580-4574-11eb-8eac-6f2435991eaa.png)
vào xem chi tiết thì vẫn edit đc bt
![image](https://user-images.githubusercontent.com/45735121/103016559-cf37de00-4574-11eb-8d0a-d453c6525e92.png)
mong muốn những OKR đã hoàn thành thì chỉ đc view, ko đc tác động lên nữa

**Comment by thaycacac** [comment]
Resolved
