### ISSUE TITLE
Chưa kiểm tra giá trị user nhập vào cho phần tiến độ KR, objective 

### ISSUE THREAD

**Issue by hoangledinh65** [lidi-team/okrs-v2#177]
**Describe the bug**
![image](https://user-images.githubusercontent.com/26743914/103046237-21e7b900-45ba-11eb-91a7-bca5990dd58a.png)

**Comment by thaycacac** [comment]
Kiểm tra cái gì???

**Comment by hoangledinh65** [comment]
OK, nếu logic là cho phép nó nhập vượt quá 100% thì cũng đc. Nhưng ô cũng phải check để nó k âm nhé.  @thaycacac 
![image](https://user-images.githubusercontent.com/26743914/103068051-e4515300-45ee-11eb-9b55-36a3fbccc12e.png)
