### ISSUE TITLE
Bug khi chuyển trang 

### ISSUE THREAD

**Issue by hoangledinh65** [lidi-team/okrs-v2#181]
**Describe the bug**
Click sang trang OKR mới thì bị lỗi
![image](https://user-images.githubusercontent.com/26743914/103060453-b6faaa00-45da-11eb-86ad-d878bdbb965d.png)
![image](https://user-images.githubusercontent.com/26743914/103060467-c2e66c00-45da-11eb-9756-632cdf4f50c8.png)

**Comment by thaycacac** [comment]
Khi nào xảy ra lỗi này?

**Comment by hoangledinh65** [comment]
Ông tạo OKR mới thì phần checkin này nó sẽ list ra danh sách OKR ở phần checkin đúng k. Nhiều quá thì nó sang trang mới. Sang trang mới thì bị lỗi
