### ISSUE TITLE
Dù dự án đã đóng, nhưng trong phần OKR của PM vẫn có tên dự án và vẫn tạo đc OKR của dự án đó 

### ISSUE THREAD

**Issue by hoangledinh65** [lidi-team/okrs-v2#186]
**Describe the bug**
![image](https://user-images.githubusercontent.com/26743914/103072353-f7b4ec00-45f7-11eb-84eb-c7d7189df376.png)
![image](https://user-images.githubusercontent.com/26743914/103072379-056a7180-45f8-11eb-9bf1-fd0f3095475d.png)

**Comment by thaycacac** [comment]
Resolved
