### ISSUE TITLE
Không thể cho phép add mới NV hoặc để NV hiện tại tiếp tục cập nhật tiến độ vào 1 dự án hoặc objective đã đủ 100%

### ISSUE THREAD

**Issue by hoangledinh65** [lidi-team/okrs-v2#216]
**Describe the bug**

**Comment by thaycacac** [comment]
Vượt tiến độ là điều có thể nhé!!!

**Comment by hoangledinh65** [comment]
@thaycacac thằng nhân viên được vượt tiến độ, trong trường hợp dự án chưa hoàn thành. Nhưng nếu trường hợp dự án đạt 100%, nghĩa là đã hoàn thành, thì việc thêm 1 thằng NV vào dự án, để nó tiếp tục contribute vào là vô lý.
