### ISSUE TITLE
Hiển thị sai Tiêu đề popup tạo mới Project

### ISSUE THREAD

**Issue by TungBeo199x** [lidi-team/okrs-v2#27]
**Describe the bug**
1. click "Thêm mới".
2. Popup hiện ra với tiêu đề "Cập nhật thông tin". chỗ nhập tên dự án có placeholder "Nhập họ và tên".
![image](https://user-images.githubusercontent.com/45735121/101313957-20b04f80-388a-11eb-9256-038f81abd5d1.png)
Mong muốn:
1. Sửa Tên popup thành "Thông tin dự án" để dùng đc cả cho cập nhật vào tạo mới
2. hiển thị placeholder là "Nhập tên dự án"

**Comment by nolann-dev** [comment]
- [x] resolved

**Comment by TungBeo199x** [comment]
closed
