### ISSUE TITLE
Thông tin cá nhân vẫn có chỗ ko bị disable

### ISSUE THREAD

**Issue by TungBeo199x** [lidi-team/okrs-v2#29]
1. vào trang thông tin cá nhân
2. vẫn có thể sửa tên, giới tính, ngày sinh
![image](https://user-images.githubusercontent.com/45735121/101369747-3d28a800-38db-11eb-82cf-c61a6ab0c7ba.png)

mong muốn:
disable toàn bộ thông tin.

**Comment by TungBeo199x** [comment]
Nếu ko làm phần update avatar thì disable luôn cả button update đi nhé

**Comment by thaycacac** [comment]
Done
