### ISSUE TITLE
Nhân viên đã bị deactive vẫn hiển thị nút detactive

### ISSUE THREAD

**Issue by TungBeo199x** [lidi-team/okrs-v2#3]
Nhân viên đã có trạng thái deactive vẫn hiển thị button "deactive tài khoản"
![bug](https://user-images.githubusercontent.com/45735121/98529186-e9ad4500-22af-11eb-9418-a74492846aa3.png)

Mong muốn:
nhân viên sau khi đã bị deactive thì sẽ khổng hiển thị button "deactive tài khoản" nữa.

**Comment by nolann-dev** [comment]
resolved

**Comment by TungBeo199x** [comment]
Oke
