### ISSUE TITLE
Đổi title thành thuần việt

### ISSUE THREAD

**Issue by TungBeo199x** [lidi-team/okrs-v2#35]
**Describe the bug**
Vẫn để lẫn tiếng việt và tiếng anh
![image](https://user-images.githubusercontent.com/45735121/101938084-5c923e80-3c15-11eb-9d72-b9b08d7b90e2.png)

Mong muốn:
- Phản hồi cho cấp dưới
- phản hồi cho cấp trên

**Comment by nolann-dev** [comment]
resolved

**Comment by thaycacac** [comment]
Done
