### ISSUE TITLE
Ko hiển thị thông tin khi bấm quay lại từ màn hình detail

### ISSUE THREAD

**Issue by TungBeo199x** [lidi-team/okrs-v2#39]
mô tả: 
- từ màn hình list OKRs bấm chọn xem chi tiết 1 OKR.
- bấm quay lại okr dashboard
![image](https://user-images.githubusercontent.com/45735121/101938870-b21b1b00-3c16-11eb-8823-142bed12af27.png)
![image](https://user-images.githubusercontent.com/45735121/101938913-c65f1800-3c16-11eb-9765-c6b39a026d28.png)

Mong muốn:
- khi bấm quay lại OKRs dashboard thì hiển thị thông tin OKRs theo chu kì hiện tại
 - sửa okrs dashboard thành OKRs Dashboard

**Comment by thaycacac** [comment]
Done
