### ISSUE TITLE
Tạo OKR: ko chọn objective cha vẫn cho chuyển sang step 2

### ISSUE THREAD

**Issue by TungBeo199x** [lidi-team/okrs-v2#41]
mở popup tạo OKRs: điền thông tin title -> bám tiếp theo
![image](https://user-images.githubusercontent.com/45735121/101939315-65840f80-3c17-11eb-8e8f-013cd7ef23f9.png)

mong muốn ko cho sang trang tiếp nếu chưa chọn parent OKRs

**Comment by thaycacac** [comment]
Done
