### ISSUE TITLE
Hiển thị rõ ràng hơn

### ISSUE THREAD

**Issue by TungBeo199x** [lidi-team/okrs-v2#46]
CFRs toàn công ty, nếu current user gửi đến người khác thì hiển thị là : Bạn đến Beach
nếu người khác đến current user thì hiển thị là: Admin đến bạn
![image](https://user-images.githubusercontent.com/45735121/101976921-8763ad80-3c7c-11eb-902d-3a8818ff618a.png)

**Comment by nolann-dev** [comment]
resolved
