### ISSUE TITLE
Đường link sai

### ISSUE THREAD

**Issue by TungBeo199x** [lidi-team/okrs-v2#48]
Vào detail recognition, nhấn vào link objective thì objective hiển thị đường link localhost
Hiện tượng tương tự ở bên detail Objective khi click vào align objective
![image](https://user-images.githubusercontent.com/45735121/101977049-5d5ebb00-3c7d-11eb-90de-420e4676b8a6.png)

**Comment by nolann-dev** [comment]
resoled
