### ISSUE TITLE
Sau khi nhấn "Hủy" không thấy hiện popup xác nhận hủy tạo OKR

### ISSUE THREAD

**Issue by TungBeo199x** [lidi-team/okrs-v2#6]
step 1 tạo OKR, nhấn "Hủy" không thấy hiện popup xác nhận xóa mà chỉ clear title của objective.
![bug](https://user-images.githubusercontent.com/45735121/98789750-5140cd00-2435-11eb-8be2-0e2a7563d5c5.png)

Mong muốn: 
nhấn "Hủy" thì hiện lên popup confirm như lúc nhấn "X"

**Comment by thaycacac** [comment]
Done
