### ISSUE TITLE
Sau khi bấm "Quay lại" ở step 3, các giá trị đã nhập trước đó ở step 2 bị clear hết

### ISSUE THREAD

**Issue by TungBeo199x** [lidi-team/okrs-v2#7]
trình tự thực hiện:
- nhập đủ KRs ở step 2, nhấn Tiếp theo
- sang step 3 nhấn Quay lại
- thông tin bị nhập ở step 2 bị clear hết

![bug](https://user-images.githubusercontent.com/45735121/98793836-ff9b4100-243a-11eb-81d7-983e3a1a3f37.png)
 
Mong muốn:
thông in đã nhập ở step 2 ko bị clear

**Comment by thaycacac** [comment]
Done
