### ISSUE TITLE
Thống nhất icon của cột "Thao tác". 

### ISSUE THREAD

**Issue by hoangledinh65** [lidi-team/okrs-v2#72]
**Describe the bug**
![image](https://user-images.githubusercontent.com/26743914/102686567-26f3e380-421b-11eb-9c1b-57f26eda3ef5.png)
![image](https://user-images.githubusercontent.com/26743914/102686569-2e1af180-421b-11eb-97a1-8bf4f0ee3ab6.png)

**Comment by nolann-dev** [comment]
resoled: center
