### ISSUE TITLE
click vào phân trang thì bị lỗi ở tab "Cập nhật tiến độ" của HR

### ISSUE THREAD

**Issue by hoangledinh65** [lidi-team/okrs-v2#76]
**Describe the bug**
![image](https://user-images.githubusercontent.com/26743914/102689866-1ef46d80-4234-11eb-8028-d83d31025b0d.png)
![image](https://user-images.githubusercontent.com/26743914/102689877-2ae02f80-4234-11eb-803f-6a667e90b521.png)

**Comment by thaycacac** [comment]
Do lúc đó đang deploy
