### ISSUE TITLE
Phần Search CFR nên có nút "Tìm kiếm" giống như các tab Quản lý khác thay vì ấn Enter. Để đồng bộ 

### ISSUE THREAD

**Issue by hoangledinh65** [lidi-team/okrs-v2#89]
![image](https://user-images.githubusercontent.com/26743914/102690942-67fbf000-423b-11eb-90a7-daf8ef12dbe0.png)
![image](https://user-images.githubusercontent.com/26743914/102690947-71855800-423b-11eb-8a5a-e501a0f64b33.png)
![image](https://user-images.githubusercontent.com/26743914/102690949-777b3900-423b-11eb-9512-9e5d64f72053.png)

**Comment by thaycacac** [comment]
Done
